 # This is an example pchtrees paramter file.

 [runtime]
 data_path = "/data/apcooper/sfw/pchtrees/data"
 iseed = -2020
 max_trees_per_file = 1000

 [output]
 output_format = 'hdf5'
 file_base = './output_trees_100_mw'
 mres = 1e7
 nlev = 128
 zred_list = './satgen_level_zred_100myr_z3_z12.txt'

 [cosmology]
 omega0 = 0.25
 lambda0 = 0.75
 h0 = 0.730000019
 omegab = 0.399999991E-01
 CMB_T0 = 2.73000002

 [powerspec]
 itrans = 1
 pkinfile = "pk_Mill.dat"
 nspec = 1.00000000
 dndlnk = 0.00000000
 kref = 1.00000000
 sigma8 = 0.899999976

 [tree]
 G0 = 0.569999993
 gamma_1 = 0.379999995
 gamma_2 = -0.999999978E-02
 eps1 = 0.100000001
 eps2 = 0.100000001

 [pfop]
 file_path  = './output_progenitors_100_mw'
 mass_limit = 1e8
